; Detection Equipment World Settings
;
; Set config values below,
;   then restart the world.
; Delete a line to reset it to default.
; 
[General Config]
;If true, IFF reflectors will always return a code regardless of their functional state. Default False
ForceEnableIff=False
;Frequency of updating IFF salts in hours. Note - this exists to make rainbow table IFF hash cracking harder. Default 1
IffResaltInterval=1
;Toggles pbapi access. If you turn this off you're cringe and I hate you. Default True
AllowPbApi=True
;Required for extended-range WeaponCore integration. Increases sync distance; set to 0 or a negative number to disable. Default 150000
OverrideSyncDistance=150000

; Controls sensors.
[Sensor Config]
;Furthest distance (in meters) a radar can lock onto a target. Don't increase this too high or syncing will break. Default 150000
MaxSensorRange=150000
;Furthest distance (in meters) a camera can lock onto a target. Cannot be further than MaxSensorRange. Default 150000
MaxVisualSensorRange=150000
;Multiplier on all radar cross-sections for all entities. Default 1
RcsModifier=1
;Multiplier on all visual cross-sections for all entities. Default 1
VcsModifier=1
;Multiplier on light armor RCS for all grids. Default 0.5
LightRcsModifier=0.5
;Multiplier on heavy armor RCS for all grids. Default 1
HeavyRcsModifier=1
;Multiplier on fatblock ("functional" block) RCS for all grids. Default 2
FatblockRcsModifier=2
;Detail level of grid radar and visual cross-section caches. Lower values are more performant but less accurate. Scales by 4^n. Default 3
CrossSectionDetail=3

; Controls how DetEq interacts with other mods.
[External Config]
;Should aggregators be able to provide targeting to WeaponCore guns?. Default True
ContributeWcTargeting=True
;Should vanilla WeaponCore magic targeting be disabled? If true, forces ContributeWcTargeting enabled. Default True
OverrideWcTargeting=True
;Maximum range for WeaponCore magic targeting, in meters. Only applies if OverrideWcTargeting is false. Set to zero or less to disable. Default -1
MaxWcMagicTargetingRange=-1
;Maximum relative error at which aggregator locks should be added to WeaponCore targeting. E_r = error / distance. Default 0.25
MinLockForWcTarget=0.25
;Conversion ratio from WC Heat to Degrees for IRS, if WC is present. Default 0.5
WcHeatToDegreeConversionRatio=0.5
